seed: 42

savestring: test
wandb_project: NEDS
log_to_wandb: true

verbosity: 0

wandb:
  use: true
  entity: null
  project: NEDS
  run_name: null

dirs:
  checkpoint_dir: checkpoints
  log_dir: results 
  dataset_cache_dir: /projects/bcxj/yzhang39/datasets # will be overwritten by the script
  dataset_dir: neurofm123/671c7ea7-6726-4fbe-adeb-f89c2c8e489b_aligned # will be overwritten by the script
  behav_dir:  data/671c7ea7-6726-4fbe-adeb-f89c2c8e489b_aligned # will be overwritten by the script
  huggingface_org: ibl-repro-ephys
  
training:
  num_epochs: 2000
  train_batch_size: 16
  test_batch_size: 16  
  shuffle_test_dataloader: false   

  save_plot_every_n_epochs: 20 
  save_every: 100 
  eval_every: 1 

  use_mtm: false
  mask_type: embd 
  mask_mode: ["temporal"]

model: 
  model_class: null  

data:
  dataset_name: ibl 
  dataset_class: ssl 

  hf_dataset_name: null   # from huggingface
  json_dataset_name: null # from json file

  train_name: train  
  test_name: test    
  train_len: null     
  test_len: null     

  LOG_EPSILON: 1.e-7 
  use_lograte: True 

  max_time_length: 100 
  max_space_length: 668   # will be overwritten by the script
  patching: true 
  sort_by_depth: false
  sort_by_region: false
  brain_region: all
  spike_augmentation: false

  include_behav: false 
  target: whisker-motion-energy # will be overwritten by the script

  load_meta: true

  num_sessions: 1 # will be overwritten by the script
  test_session_eid: ["671c7ea7-6726-4fbe-adeb-f89c2c8e489b"] # will be overwritten by the script

  split_method: session_based

  use_aligned_test: False

method:
  model_kwargs: 
    method_name: ssl 
    use_lograte: true
    loss: poisson_nll 
    output_size: 2
    clf: false
    reg: false

  dataset_kwargs: {}

  dataloader_kwargs:
    pad_dict: 
      spikes:
          dim: 0
          side: right
          value: 0
          truncate: null
          min_length: null
      

optimizer:
  gradient_accumulation_steps: 1
  lr: 2.e-4
  wd: 0.01
  eps: 1.e-8
  warmup_pct: 0.15 
  gamma: 0.95  
  div_factor: 10  
  scheduler: cosine 
  